---
title: "Matrix_exercises"
author: "Guillem"
date: "22 de enero de 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pregunta 1

```{r}
A = matrix(c(0, 1, -2, 2, 3, -1, 1, -1, 5), nrow = 3,  byrow = TRUE)
B = matrix(c(1, -1, 2, 1, 2, -2, 2, -2, -1, 2, 1, 2), nrow = 3, byrow = TRUE)
C = matrix(c(2, 0, 1, -4))

A%*%B
B%*%C
t(B)
t(B) %*% A
t(C) %*% t(B)
```

# Pregunta 2

```{r}
A = matrix(c(0, 1, 0, 1), nrow=2, byrow = TRUE)
B = matrix(c(-1, -1, 0, 0), nrow = 2, byrow = TRUE)

library(expm)
(A + B)%^%2 == A%^%2 + 2*A%*%B + B%^%2

(A + B)%^%3 == A%^%3 + 3*(A%^%2)%*%B + B%^%3
```
# Pregunta 3

```{r}
A = matrix(c(-1, 1, -2, 1, 1, 0, 2, 1, 1), nrow = 3, byrow = TRUE)
B = matrix(c(-1, 2, 3, 4, 5, 1, 2, 1, 3, 2, 0, 4, 4, 7, 7), nrow=3, byrow = TRUE)

qr(A)$rank
qr(B)$rank
```

# Pregunta 4

```{r}
A = matrix(c(1, 2, 0, 0, 1, -1, 0, 0, 2), nrow = 3, byrow = TRUE)
B = matrix(c(1i, 0, 0, 0, 0, 1, 1, 1i, 0), nrow = 3, byrow = TRUE)

solve(A)
solve(B)
```

